[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "arches-he-location-extensions"
description = "An Arches application extension that provides location-based functionality and enhancements for Arches-based projects. Designed for easy integration with Historic England's Arches projects."
readme = {file = "README.md", content-type = "text/markdown"}
version = "1.0.0"
license = {text = "GNU AGPL3"}
authors = []
maintainers = [{name = "Historic England", email = "donotreply@historicengland.org.uk"}]
keywords = ["arches", "extension", "django", "heritage", "historic-data", "location", "gis"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Framework :: Django",
    "Framework :: Django :: 4.2",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Information Technology",
    "License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)",
]
requires-python = ">=3.10"
dependencies = [
    "arches>=7.6.22,<8.0.0",
]

[project.urls]
Homepage = "https://github.com/HistoricEngland/arches-he-location-extensions"
Repository = "https://github.com/HistoricEngland/arches-he-location-extensions.git"
Issues = "https://github.com/HistoricEngland/arches-he-location-extensions/issues"
Changelog = "https://github.com/HistoricEngland/arches-he-location-extensions/releases"

[project.optional-dependencies]
dev = [
    "livereload",
    "sst",
    "coverage",
    "django-silk==5.1.0",
    "pre-commit==3.8.0",
    "black==24.4.2",
]

[tool.setuptools.packages.find]
include = ["arches_he_location_extensions*"]
exclude = ["arches_he_location_extensions.logs*"]

[tool.setuptools]
include-package-data = true
