server {

  location /featureserver/ {
    proxy_pass http://pg-feat-arches-he-location-extensions:9000/;
  }

  location /tileserver/ {
    proxy_pass http://pg-tile-arches-he-location-extensions:7800/tileserver/;
  }

  location / {
    proxy_pass http://arches-he-location-extensions:8000/;
  }

}